# Generated by Django 4.2 on 2023-05-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_cinema_href_alter_cinema_poster"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cinema",
            new_name="Movies",
        ),
    ]
