# Generated by Django 4.2 on 2023-05-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_rename_cinema_movies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Movies",
        ),
    ]
