# Generated by Django 4.2 on 2023-05-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "film_title",
                    models.CharField(max_length=50, verbose_name="Название фильма"),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "userid",
                    models.CharField(max_length=50, verbose_name="ID пользователя"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="movies",
            name="poster",
            field=models.ImageField(
                upload_to="D:\\projects\\website\\web\\media/", verbose_name="Постер"
            ),
        ),
    ]
