# Generated by Django 4.2 on 2023-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_comments_alter_movies_poster"),
    ]

    operations = [
        migrations.AddField(
            model_name="movies",
            name="trailer_href",
            field=models.CharField(
                default="href", max_length=100, verbose_name="Ссылка на трейлер"
            ),
            preserve_default=False,
        ),
    ]
