# Generated by Django 4.2 on 2023-05-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_movies_trailer_href"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="userid",
            new_name="username",
        ),
    ]
