# Generated by Django 4.2 on 2023-05-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_userid_comments_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="film_href",
            field=models.CharField(
                default="Tenet", max_length=50, verbose_name="Ссылка"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="username",
            field=models.CharField(max_length=50, verbose_name="Логин пользователя"),
        ),
    ]
